### ISSUE TITLE
.value-label: Add Hyphens when Available

### ISSUE THREAD

**Issue by FlorianWendelborn** [3YOURMIND/kotti#479]
This should probably be added to the main kotti class, instead of being overwritten in the usages:

```scss
.label-value {
	hyphens: auto;
}

@supports not (hyphens: auto) {
	.label-value {
		word-break: break-all;
	}
}
```
