### ISSUE TITLE
Support HTML5 Form Validation

### ISSUE THREAD

**Issue by dodekeract** [3YOURMIND/kotti#9]
E.g.

```html
<input type="email"/>
```

With an invalid value the browser will activate the `:invalid` selector:

```css
input:invalid {
	border-color: $red-500;
}
```
